### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#1]
There is no wiki on the github project site

**Comment by alarshi** [comment]
Fixed for now, will edit as we go along

**Comment by ricardotaborda** [comment]
I do not see this fixed. When I click in the wiki tab nothing happens. It is empty.

**Comment by alarshi** [comment]
I can't access Wiki tab, but I could see the wiki page on out group repository.

**Comment by alarshi** [comment]
I am trying to push this project but couldn't: https://github.com/jzhang1091/2D-Heat-Convection-by-FDM.wiki.git

**Comment by ricardotaborda** [comment]
I am not sure what you are trying to push. The wiki needs to be created by the owner of the project, after that all members should be able to contribute to it. @jzhang1091 is the owner, so he should start it.

**Comment by alarshi** [comment]
Oh, that explains. Thank you.

**Comment by jzhang1091** [comment]
I have created Wiki page. Now the issue will be closed.

**Comment by ricardotaborda** [comment]
The wiki of this project is very poor. It offers almost no useful documentation. 

(I explained in class how to include figures. Most other groups have done it successfully.)

**Comment by luh1202** [comment]
I am sorry Ricardo, I have updated our wiki page.
