### ISSUE TITLE
Forks

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#10]
None of you have forked this project yet. You should work through forks, do individual commits and pushes to your won forked repositories, and then submit pull requests to the main project repository.

**Comment by ricardotaborda** [comment]
If you have already created the forks, why not to comment and close this issue ticket?

**Comment by alarshi** [comment]
I am sorry, could you please close this issue.

**Comment by jzhang1091** [comment]
All of us have created the forks. Now the issue will be closed.
