### ISSUE TITLE
Full {...} blocks

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#12]
Please make sure you use complete `{...}` blocks, even for single-line instructions.

**Comment by jzhang1091** [comment]
All brackets {...} have been checked.

**Comment by ricardotaborda** [comment]
Several files still have single line `if` and `for` blocks without any bracket.

**Comment by luh1202** [comment]
I checked all the files and they all have {...} now.
