### ISSUE TITLE
Add files to gitignore

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#23]
Please add the files

`.cproject`
`.project`

to the `.gitignore` file to avoid `git status` picking on the eclipse configuration files.

**Comment by ricardotaborda** [comment]
Please also add the files

`main`
`readin`

so that once compiled, git can ignore the executables.

**Comment by jzhang1091** [comment]
.gitignore file has been updated
