### ISSUE TITLE
Makefile to delete doxygen directories

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#24]
Please add to the `cleanall` instruction in `Makefile` the instruction of deleting the `html` and `latex` directories that are created when one runs `doxygen`. In essence, the result of `cleanall` should be to restore the content of files in the project to its "raw" version, before compiling and before creating the documentation.

**Comment by jzhang1091** [comment]
A revised Makefile is generated to make sure that "cleanall" will remove all the executive files.
