### ISSUE TITLE
Doxygen configuration file

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#3]
Add the Doxygen configuration file to your project and make sure the html and latex directories are included in the .gitignore file to avoid these directories being uploaded to the repository.

**Comment by ricardotaborda** [comment]
Almost a week without progress on this.

**Comment by jzhang1091** [comment]
A doxygen configuration file named doxygen.dxg has been added.
