### ISSUE TITLE
Makefile missing

### ISSUE THREAD

**Issue by luh1202** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#31]
Did we mistakenly delete the makefile?

**Comment by jzhang1091** [comment]
I don't know who deleted it by mistake, but I can push a new Makefile.

**Comment by ricardotaborda** [comment]
Still missing in the main directory.

**Comment by ricardotaborda** [comment]
BTW, @jzhang1091 you were the one who deleted it. It is easy to track it down. You deleted in commit tagged `db0b0a2751`.

**Comment by jzhang1091** [comment]
Sorry for this. I originally wanted to move the Makefile to /src subdirectory, but I forgot to add the new one. Now this file has been pushed.
