### ISSUE TITLE
Makefile location

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#32]
Your `Makefile` should be in the code directory. I should not go down into the `src` directory to run the `make` command. I should be able to download the code, and run `make` straight from the main directory of the code. Your latest re-structuring of the files spoiled this functionality and the `src` directory itself is missing the `Makefile`.

**Comment by ricardotaborda** [comment]
You have the `Makefile` in the `src` directory. That is fine, because you need one there. But you need a parent `Makefile` in the main project directory, which is the one that would do the correct deleting of html and latex and compile the whole thing.

**Comment by jzhang1091** [comment]
A parent Makefile in the main directory has been added.
