### ISSUE TITLE
Lon list of parameters in functions

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#36]
The functions 

* `implicit_T1`, 
* `explicit_T1`, 
* `set_psi`, 
* `set_horizontal_velocity`, 
* `set_vertical_velocity`, 
* `store_params`, 
* `write_logfile`,

all have a very, very long list of parameters. You should create structs to help you package some of those parameters so that call to functions and function prototypes and implementations can be read easily by other developers and to make them succinct.

**Comment by jzhang1091** [comment]
Use struct to store parameters
