### ISSUE TITLE
Long `while` loop in `store_params`

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#38]
The function `store_params` in `file_io.coo` has an extremely long `while` loop. It seems clear that you need to come up with a better strategy to deal with what happens at every one of those `if` statements. I suggest you create a function that can take in parameters and deal with in a more compact manner.

**Comment by jzhang1091** [comment]
Using a new function pass_vari() to pass the variables when the keyword is compatible.
