### ISSUE TITLE
Overloading

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#39]
Functions like

* `read_double`
* `read_int`
* `read_string`

and 

* `check_vari_double`
* `check_vari_int`
* `check_vari_string`

Are an excellent case for overloading.

http://www.learncpp.com/cpp-tutorial/76-function-overloading/

**Comment by jzhang1091** [comment]
overloading functions have be used.

**Comment by ricardotaborda** [comment]
This is not fixed! Do not close tickets just for closing them. I am looking at the latest version of the code and this has not been fixed yet. If you have fixed in a local version, you cannot close a ticket unless a fixed version has been uploaded to the repository.

**Comment by jzhang1091** [comment]
overloading functions have been pushed.
