### ISSUE TITLE
Doxygen documentation

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#42]
There are too many functions in header files without the most basic documentation to be captured by Doxygen. Each person is responsible for documenting its own functions. You should have done this as you were writing the code, as opposed to wait until the end.

**Comment by ricardotaborda** [comment]
In fact, if one generates the doxygen documentation, the result is pretty much nothing at all. Only the same basic info from the readme file.

**Comment by jzhang1091** [comment]
I have documented the functions in the file_io.h, utility.h and the mainpage in the main file.

**Comment by luh1202** [comment]
I have added Doxygen documentation for every file
