### ISSUE TITLE
Use of curly brackets

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#43]
Inconsistent throughout the code. Some times in the same line of functions and if or for loops. Sometimes in the next line. Please decide on a particular style and stick to it.

**Comment by luh1202** [comment]
Many of my commits just now were just about brackets and minor changes, I should have got it done and commit only once.
Sorry for the mess.

**Comment by luh1202** [comment]
I have adjusted all loops and functions to the same line.
Thank you!
