### ISSUE TITLE
Compiling and use of GSL library

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#44]
Your code does not compile. 

I understand you are using the GSL library and in order for me to compile in my own computer, I should then install the GSL library. But you should recall is that the basic standard is that the code should compile in the HPC. But your code does not compile there either.

The README file does not provide information about it. The Wiki does not provide information either. The Makefile in the `src` directory does not load the library either. In other words, if I were an inexperience user I would be stuck.

This is what needs to happen. If I am logged in to the UofM HPC I should be able to do the following without any errors along the way

```bash
> ssh penguin1.memphis.edu -l username 
> git clone git@github.com:ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM.git
> cd 2D-Heat-Convection-by-FDM
> module load gsl/1.16/gcc.4.4.7
> make
```

And the code should compile without any problem. If I cannot do that tomorrow by the time you showcase your code in front of the class, then what?

**Comment by jzhang1091** [comment]
Update the README.info, which tell the users should change the links in "Makefile" to their local gsl library location before make.

**Comment by ricardotaborda** [comment]
Tomorrow, in class, I will not make changes to anything. It either compiles or doesn't. I am not going to waste time making changes. I will have a terminal open on my local computer, and one open in HPC. If the code does not compile, then you won't be able to run your Demo.

**Comment by jzhang1091** [comment]
Ok, we will modify the Makefile to the gsl library location in HPC and test the program.

**Comment by alarshi** [comment]
Modified the make file for HPC, it should compile now
