### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#6]
A readme file may not be necessary, but if included, the readme file should be about information essential to the user to compile the code and run it. A better practice is to include the kind of information currently in the readme file in the wiki page of the project.

**Comment by ricardotaborda** [comment]
Almost a week without progress on this.

**Comment by alarshi** [comment]
Deleted readme and updated wiki
