### ISSUE TITLE
Code structure and collaboration

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#7]
You are writing different program files with independent "main" functions in them. This shows you are not truly collaborating in writing a software together. Writing different main codes would make sense if the individual pieces of it are structured to also be part of the larger main program. But that is not the case here. The code needs to be structured to work as a whole even if some pieces are designed to work independently for testing and development purposes.

**Comment by ricardotaborda** [comment]
Almost a week without progress on this.

**Comment by jzhang1091** [comment]
Several functions written by the group members have been added to one main file.
