### ISSUE TITLE
Vertical spacing

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#8]
Vertical spacing of the files `id2.cpp` and `input_id_function.cpp` is not consistent with the style used for other source code files.

**Comment by ricardotaborda** [comment]
Almost a week without progress on this.

**Comment by jzhang1091** [comment]
id2.cpp and input_id_function.cpp have been removed since the function can be declared in the main file.

**Comment by ricardotaborda** [comment]
Beyond the initial two files for which this item was brought up, I can see now very irregular use of vertical spacing throughout the files of the code. Some files have excessive, often unnecessary use of vertical spaces and other files have no vertical separations whatsoever. `initial_tem.h` for instance is very bad style coding. Everything smashed up and crowded.
